#!/bin/bash
set -e
eval "$("$(dirname $0)"/adr-config)"

reldir=.

function mkrel() {
	local d=$reldir/$1
	echo ${d#./}
}

function absdir() {
	(cd "$(dirname $1)" && pwd -P)
}

while [ "$(absdir $reldir)" != / ]
do
	if [ -f "$(mkrel .adr-template-dir)" ]
	then
    mkrel "$(cat "$(mkrel .adr-template-dir)")"
		exit
	elif [ -d "$("$adr_bin_dir/_adr_dir")/templates" ]
	then
		echo "$("$adr_bin_dir/_adr_dir")/templates"
		exit
	else
		reldir=$reldir/..
	fi
done
echo $adr_template_dir
