#!/bin/bash
set -e
eval "$("$(dirname "$0")"/adr-config)"

title="$(head -2 "$("$adr_bin_dir/_adr_file" "$1")" | grep -E '^title: (.*)' | cut -c 8-)"

if [ ! -n "$title" ]
then
    title="$(head -2 "$("$adr_bin_dir/_adr_file" "$1")" | grep -E '^# (.*)' | cut -c 3-)"
fi

echo $title
